src/CashuMint.ts, src/CashuWallet.ts, src/DHKE.ts, test/crypto.scheme.test.ts, test/wallet.test.ts, tsconfig.json
=> Enable all strict type checking options

src/CashuMint.ts, src/CashuWallet.ts, src/DHKE.ts, src/model/BlindedMessage.ts, src/model/BlindedSignature.ts, src/model/Split.ts, src/model/types/SerealizedBlinedSignature.ts, src/model/types/Token.ts, src/model/types/index.ts, src/utils.ts
=> Extract types

.prettierignore, .prettierrc, package-lock.json, package.json
=> add prettier

src/CashuWallet.ts
=> Return unused proofs as change in send function

package.json, src/CashuMint.ts, src/CashuWallet.ts, src/model/types/index.ts, src/utils.ts, test/wallet.test.ts, tsconfig.es5.json, tsconfig.json
=> Wallet tests

README.md, src/CashuMint.ts, test/wallet.test.ts
=> CashuMint: remove mintApiRoot and mintPort, use mintUrl only

src/CashuMint.ts, src/model/types/index.ts
While testing the new release version with nutstash, i encountered a bug when trying to melt. The issue is, that the preimage might be null sometimes, and if that's the case, we get a 'bad response', eventhough the payment went through.
=> fix melt response bug

.github/workflows/node.js.yml, package-lock.json, package.json, src/CashuMint.ts, src/DHKE.ts, test/crypto.scheme.test.ts
make keysetId url safe
closes #52
=> CashuMint: getKeys Add optional keysetId parameter

src/CashuMint.ts, src/CashuWallet.ts, test/wallet.test.ts
=> NUT-08: Dynamic amount of tokens for change

src/CashuWallet.ts, src/index.ts, src/model/types/index.ts, src/utils.ts, test/wallet.test.ts
CashuWallet: remove getDecodedLnInvoice, update payLnInvoiceWithToken & receive now returns a token ( #43  )
Index: export decode as getDecodedLnInvoice and export deriveKeysetId
Utils: add deriveKeysetId function
Types: add PaymentPayload, SendResponse, ReceiveResponse & PayLnInvoiceRespons
closes #43
=> add deriveKeysetId function

src/CashuMint.ts, src/index.ts, src/model/types/index.ts
[CashuMint: add static function](https://github.com/cashubtc/cashu-ts/commit/efb99d39b8f25bbe7ab8d6c8da8b859746939241)
[add TokenEntry type](https://github.com/cashubtc/cashu-ts/commit/b8fe4ececa60b698c7e34b47b1e1637ca35152ce)
=> CashuMint: add static functions

src/index.ts
Adding onto #34, not sure if this was missed or intentional, but I need to setup some custom axios config in cashu.me. Saw this function, but it was not exported at the top level.
=> export `setupAxios` for end user

README.md, package-lock.json, package.json, src/CashuWallet.ts, test/wallet.test.ts
=> CashuWallet: make keys constructor param optional

src/model/types/index.ts
=> Response type of /info endpoint

src/CashuWallet.ts
Adds some comments to `CashuWallet.ts`
=> CashuWallet.ts: add comments

.github/workflows/coverage.yml, .github/workflows/node.js.yml, package-lock.json, src/CashuWallet.ts, test/wallet.test.ts
=> Hotfix tests

package-lock.json, package.json, src/CashuMint.ts
Some build tools won't be able to find `@noble/hashes`. so we install it manually
- add `@noble/hashes` dependency
- upgrade some deps
=> add hashes dep and upgrade other deps

.github/workflows/version.yml
GH workflow for releasing on npm registry
- add workflow file
- added NPM_TOKEN to repo secrets
=> pipeline for npm release

src/model/types/index.ts
=> add unit to Token

package-lock.json, package.json, src/CashuMint.ts, src/CashuWallet.ts, src/base64.ts, src/legacy/nut-04.ts, src/legacy/nut-05.ts, src/model/types/index.ts, test/request.test.ts, test/wallet.test.ts
Implements: https://github.com/cashubtc/nuts/pull/141
and https://github.com/cashubtc/nuts/pull/136
- nothing changes for the implementor
=> NUT-04 and NUT-05: Add `state` enum field

.github/workflows/format.yml, package.json, src/CashuMint.ts
=> Format checker in gihtub pipeline

README.md
Merge `main` into `development`
=> Development: sync to main

README.md
=> Add melt example to README

.github/workflows/nutshell-integration.yml
Replaces https://github.com/cashubtc/cashu-ts/pull/161
=> Update Nutshell Docker image to 0.16.0

src/base64.ts
Fixes base64url encoding (which doesn't exist in my Chrome)
=> v1.1.0 rc1 fix base64url

package-lock.json, package.json
=> bump cashu/crypto to 0.2.7

src/cbor.ts
Paired with @kodylow
Upstreaming some stronger types we added for decoding cashuV4 tokens. Helpful for projects with strict ESLint rules.
Shouldn't affect runtime whatsoever. (one exception... added a runtime check within decode map to verify that keys are a valid type. Tests still pass.)
- Added stronger types for decode CBOR functions (removed `any`s)
---
Future TODOs
* **Add stronger types on the encode functions.** We only needed the decode functions, so we didn't touch the others. Also, I'm not sure what everyone will be using those functions for, so I can't make a decision on narrowing the parameter type of `encodeCBOR`.
=> Stronger type safety for cbor decode functions

README.md
=> fix docs link in readme

.npmignore
Removes unnecessary files from npm package.
=> ignored files for npm

src/CashuWallet.ts, src/model/OutputData.ts, src/utils.ts, test/integration.test.ts, test/wallet.test.ts
Replaces https://github.com/cashubtc/cashu-ts/pull/236, but is based of `blinding` branch.
=> Fix deterministic secrets

src/utils.ts
Mostly readability changes
- Removed redundant check for amount = 0
=> SplitAmount Refactor

README.md
Updated README: NUT-18 is implemented. 
See docs: https://cashubtc.github.io/cashu-ts/docs/main/classes/PaymentRequest.html
and tests: https://github.com/ildella/cashu-ts/blob/main/test/paymentRequests.test.ts
=> NUT-18 is implemented, updating README. 

src/model/types/mint/responses.ts
=> fix: add icon_url to GetInfoResponse

src/index.ts
In a recent change the export of `OutputData` was removed, this adds it back in.
- Export `OutputData`
=> export OutputData

README.md, examples/paymentApi_example.js
Added `getDecodedToken` example in the README and an example of firebase API to receive cashu payments in the folder /examples/
=> Added getDecodedToken example in the README and an example of firebase API to receive cashu payments

src/CashuMint.ts, src/CashuWallet.ts, src/legacy/nut-04.ts, src/legacy/nut-05.ts, src/model/types/mint/responses.ts
adds new optional fields
- add new optional fields on the mint and melt responses
=> update response types

.github/workflows/format.yml
Runs format.yml workflow on Pull Requests
=> Run format check on PR

src/crypto/common/index.ts, src/crypto/util/utils.ts
Fixes import syntax for `buffer` package / polyfill
- import from `'buffer' instead of `'buffer/'``
=> Buffer fix

src/WSConnection.ts
=> Add onClose method to WSConnection

.github/workflows/node.js.yml
Node tests were not running on Pull Request. This fixes.
=> Chore: update CI to include Node tests on PR
