src/CashuMint.ts
src/axios.ts
src/utils.ts

This would allow users to do things like 
```typescript
import { setupAxios } from './axios';
setupAxios({ timeout: 1000 })
```
or
```typescript
setupAxios({
'httpAgent': new SocksProxyAgent(`socks5h://${torConfig.ip}:${torConfig.port}`),
'httpsAgent': new SocksProxyAgent(`socks5h://${torConfig.ip}:${torConfig.port}`),
})
```

allow custom axios instance

---

src/CashuWallet.ts
src/base64.ts
src/utils.ts

update Buffer imports from
```
import { Buffer } from 'buffer';
```
to
```
import { Buffer } from 'buffer/';
```
to use the Buffer npm pkg and not nodes Buffer
from https://www.npmjs.com/package/buffer
```
To depend on this module explicitly (without browserify), require it like this:
var Buffer = require('buffer/').Buffer  // note: the trailing slash is important!
To require this module explicitly, use require('buffer/') which tells the node.js module lookup algorithm (also used by browserify) to use the npm module named buffer instead of the node.js core module named buffer!
```

update Buffer imports

---

src/CashuWallet.ts

I think we can make this function public. It gives some more flexibility to wallets, on how they would like to receive tokens.

make token entry public

---

README.md

I tried to run the example provided in `README.md` only to run into a Type Error.
`proofs` in the `invoiceHasBeenPaid` function should be destructured instead of being directly referenced.
The call signature of `wallet.requestTokens` is as follows:
```ts
CashuWallet.requestTokens(amount: number, hash: string, AmountPreference?: Cashu.AmountPreference[] | undefined): Promise<{
proofs: Cashu.Proof[];
newKeys?: Cashu.MintKeys | undefined;
}>
```

Fix Code Typo in README.md

---

src/CashuMint.ts
src/utils.ts
test/utils.test.ts

I've been having an issue where mint urls with a trailing `/` will cause errors in this library as it ends up with duplicate `/` in the mint urls. This adds a `joinUrls` function to remove duplicate `/` when joining url instead of just appending the path to the mint url string, 
The other way I thought to do this is to strip the trailing `/` when creating a new mint. However, since these functions are publicly exposed think its best to handle mint urls that maybe passed in with a trailing `/`.
...
Add: Util `joinUrls`

improve: handle trailing and duplicate `/` in mint urls

---

src/CashuMint.ts
src/CashuWallet.ts
src/model/types/index.ts
test/wallet.test.ts

implements [update](https://github.com/cashubtc/nuts/pull/34) in [nut-06](https://github.com/cashubtc/nuts/blob/main/06.md) deprecating the `amount` field in `PostSplitRequest` and only returning `promises` in `PostSplitResponse`.
Partly overlaps with #77

Update NUT-06: deprecate `amount` in `PostSplitRequest`

---

README.md
package-lock.json
package.json
src/CashuWallet.ts
src/model/types/index.ts
src/utils.ts
test/utils.test.ts
test/wallet.test.ts

Merged PRs for deprecated amount field and custom split amounts.
- Merge PRs

Merge custom splits and nut 6

---

.github/workflows/coverage.yml
.github/workflows/node.js.yml
package-lock.json
src/CashuWallet.ts
src/index.ts
src/model/types/index.ts
src/utils.ts
test/utils.test.ts
test/wallet.test.ts

Added a decodeInvoice utility function that takes in a bolt11 invoice and returns an object of type InvoiceData
```ts
type InvoiceData = {
paymentRequest: string;
amountInSats: number;
amountInMSats: number;
timestamp: number;
paymentHash: string;
memo: string;
expiry: number;
};
```
- Added type InvoiceData
- Added decodeInvoice to utils.ts
- Added test

added decodeInvoice util

---

src/CashuWallet.ts
src/index.ts
test/wallet.test.ts

This adds the capability to receive a raw token instead of only encoded ones to CashuWallet.receive
- added some basic parsing logic to check wether parameter is string or Token
- added test case

raw token receive

---

src/model/types/index.ts
src/utils.ts

After updating to 0.9.0 and testing out the util function "decodeInvoice", I noticed that the property "paymentRequest" is undefined. I assume that it should hold the invoice string.
Since the variable "invoiceData" is initialized as empty object, I've also updated the type "InvoiceData" because all properties (except "paymentRequest") could be undefined for whatever reason.
Please let me know if I am missing something @Egge21M @BilligsterUser @gandlafbtc

add missing paymentRequest, update InvoiceData type

---

src/model/Errors.ts
src/request.ts
test/wallet.test.ts

Exception is now identifiable as HttpResponseError providing a status code. 
**Breaking?** We no longer look for error messages on `ok` responses. (HTTP2XX)
This is a small PR as part of an ongoing effort to address https://github.com/cashubtc/cashu-ts/issues/86
...
- Exception is now identifiable as HttpResponseError providing a status code. 
- **Breaking?** We no longer look for error messages on `ok` responses. (HTTP2XX)

Refactored `request` error handling

---

src/CashuMint.ts
src/CashuWallet.ts
src/DHKE.ts
test/dhke.test.ts
test/secrets.test.ts
test/wallet.test.ts

:warning: This PR will affect the restore process of wallets that implement determinsitic secrets. Wallets that implement this PR will have to initiate a 'self-spend' of all ecash after upgrading, in order to ensure the ecash will be recoverable.  :warning: 
The secrets that cashu-ts uses is a base64 string, which makes it incompatible for restoring ecash accross clients that use hex secrets. The spec recommends to use a hex string, so that's why we switch.
- change from b64 to hex
- fix tests

switch to hex secrets

---

migration-1.0.0.md
package-lock.json
package.json
src/CashuWallet.ts
test/base64.test.ts
test/integration.test.ts
test/wallet.test.ts

This PR contains a few changes that I would like to add to v1 release, because they contain some interface changes.
- support for simple P2PK send and receives 
- change optional function parameters  to `options` object
- add cashu-crypto library

P2PK, cashu-crypto lib, options object

---

src/CashuMint.ts

Clarifies that getKeys fetches the keys of *all* active keysets if no `keysetId` parameter is given.

Chore: `getKeys()` comment fix

---

.github/workflows/node.js.yml
src/CashuMint.ts
src/CashuWallet.ts
src/model/types/index.ts
test/integration.test.ts
test/request.test.ts
test/wallet.test.ts

Only renamed objects, might need resorting of imports for formatting reasons.

Chore: Equalize MintQuote and MeltQuote object names

---

migration-1.0.0.md
src/CashuWallet.ts
test/integration.test.ts
test/request.test.ts
test/wallet.test.ts

- changed constructor to use options param
- added getter for unit field
- ...
- ...

Get unit method

---

src/CashuWallet.ts

I had some issues working with sending / receiving usd but being able to specify the keysetId made things a lot easier. Otherwise I have to specify the list of keys and it gets rather messy. 
- added keysetId to options for `send` and `receive`.

Fixes bug with sending/receiving usd (other units)

---

src/CashuWallet.ts
src/model/types/index.ts

- calling `CashuWallet.send()`  with a keyset for units other than 'sat'
-  `payLnInvoice` required a `meltQuote` even though it creates one.
Very small changes. I just added `keysetId` to the `send` function and passed it to `getKeys`.
I also made it so that in `getKeys`, if the keysetId parameter is`undefined` it will not be compared to `this._keys.id`
...
- I add
- ...
NOTE: `npm run test` failed all tests even before I made changes:

Bug/send keyset + make meltQuote optional in payLnInvoice

---

src/CashuMint.ts
src/utils.ts

Mint URLS containing a trailing slash at the end fail to connect because of that slash. this fix includes a sanitizeurl function that removes the trailing slash when it it exists
...
- ...sanitizeURL function in /src/utils.ts for handling trailing slash
- ...utilize sanitizeUrl function in /src/CashuMint.ts in the `get MintUrl` method in the CashuMint class

Fix: Handle trailing slashes in mint urls supplied to the CashuMint class

---

src/CashuWallet.ts

Option in `mintTokens` was called `amountPreference` but it's `preference` everywhere else.

Fix: rename `amountPreference` to `preference`

---

README.md
migration-1.0.0.md
src/CashuMint.ts
src/CashuWallet.ts
src/model/types/index.ts
test/integration.test.ts
test/request.test.ts
test/wallet.test.ts

This PR adds the `GET quote` methods from the v1 api and the `expiry` and `paid` attributes to the models that are defined in NUT-4 and 5. 
**Attention! This PR changes method names!!!!** 
`getMintQuote` is **REPLACED** as this method creates a new quote and the old naming is confusing with relation to the API.
```ts
getMintQuote(amount: number); -> mintQuote(amount: number)
getmeltQuote(request: string) -> meltQuote(request: string)
```
New GET methods
```ts
getMintQuote(quoteId: string)
getMeltQuote(quoteId: string)
```
```ts
SplitPayload -> SwapPayload
SplitResponse -> SwapResponse
```
For minting new tokens, most wallets used this flow: request mint quote, and then keep calling the `mint` function until it doesn't return an error anymore (but returns ecash). This is not very elegant …

Add `GET quote` methods and rename methods

---

src/CashuMint.ts
src/CashuWallet.ts
src/base64.ts
src/legacy/nut-06.ts
src/model/types/index.ts
test/wallet.test.ts

Implements changes for the contact field in NUT-06 (https://github.com/cashubtc/nuts/pull/117) and monkey-patches responses from old mints so that they can be deserialized. Deprecated code block can be removed once all mints upgraded.
- new wallet method `getMintInfo` 
- tests

Nut-06-fix-contact

---

migration-1.0.0.md
src/CashuMint.ts
src/CashuWallet.ts
src/utils.ts
test/integration.test.ts
test/request.test.ts
test/wallet.test.ts

Feedback from the hackday was that naming of some user facing methods of `CashuWallet` were not clearly named. This PR addresses this issue. It also changes the names of corresponding `CashuMint` methods to reflect the protocol spec more closely.
- Changed `CashuWallet.mintQuote` to `CashuWallet.createMintQuote`
- Changed `CashuMint.mintQuote` to `CashuMint.postMintQuote`
- Changed `CashuWallet.getmintQuote` to `CashuWallet.checkMintQuote`
- ... The same for `meltQuote` and `getMeltQuote`

Naming Methods Mint/Melt

---

package-lock.json
package.json
src/cbor.ts
src/utils.ts
test/utils.test.ts

This PR changes the way `handleTokens` works. It also adds reading the newly proposed v4 Token format. V4 token are parsed and mapped to output the exact same structure as v3 Token to make handling easier. Consumers of `getDecodedToken` receive a stable result.
- Removed deprecated token format support (pre v3)
- Removed test cases for deprecated token formats
- `handleTokens` now parses the version and decodes accordingly.

Reading V4 Token

---

migration-1.0.0.md

Between the time that the migration guide was written and the v1.0.0 release there were a few minor changes.
I upgraded from rc.5 to the release version and found changes to the `MintQuoteResponse`, `MeltQuoteResponse`, and return types of `receive` and `receiveTokenEntry`
Updated migration guide with discrepancies I found, but this is not necessarily all of them

update v1.0.0 migration guide

---

src/base64.ts
src/cbor.ts
src/index.ts
src/model/types/index.ts
src/utils.ts
test/cbor.test.ts
test/utils.test.ts

Added a util function `getEncodedTokenV4` that creates a V4 formatted token string from a `Token`. This is opt in for now and does not change the behaviour of `getEncodedToken`. Once the ecosystem broadly supports V4 we should consider adjusting `getEncodedToken` to default to V4 and falling back to V3 if required (base64 encoded keyset id for example).
- Fixed CBOR encoder
- Added `getEncodedTokenV4` utility function

Feature: Creating V4 Token

---

src/CashuWallet.ts
test/integration.test.ts
test/wallet.test.ts

The `receiveTokenEntry` and `receive` methods in the `CashuWallet` class now properly handles errors and returns specific error messages instead of a generic one. 
Changes look more than they are. I'm only removing the `try {} catch {}` block because we aren't doing anything with the error. This lets the error be handled downstream.

Fix error handling in `receive`

---

README.md

token v4 was not mentioned in the readme
reading added in https://github.com/cashubtc/cashu-ts/pull/144
writing added in https://github.com/cashubtc/cashu-ts/pull/166

add token v4 to readme

---

src/CashuWallet.ts
test/integration.test.ts

added option to sign P2PK proofs if a private key is provided

`meltTokens` signs P2PK proofs

---

src/CashuWallet.ts
src/model/types/wallet/payloads.ts
test/integration.test.ts

Implements https://github.com/cashubtc/nuts/pull/144/

NUT-05: description for invoice, integration test without bolt11 decode

---

.eslintrc.json
src/CashuMint.ts
src/CashuWallet.ts
src/utils.ts

This PR adds some rules to eslint that will then enforce explicit type annotation on function parameters (including arrow functions). This makes the library source code a bit more verbose, but helps with readability.
- Add linter rules
- Adjust code to make the linter happy

DX: Enforce explicit type annotations on function parameters

---

src/CashuWallet.ts
src/legacy/cashu-ts.ts
src/model/types/index.ts
src/utils.ts
test/utils.test.ts
test/wallet.test.ts

- getPreferences checks input amouts against the amounts of the keys
- keepPreferences and sendPreferences as different optional parameters in createSplitPayload.
- modify splitAmount behaviour -in case of no specified preference- to create amounts not from powers of 2
but from the amounts of the keyset instead.
- splitAmount reorders its outputs by descending/ascending order.

Amount Preferences Fixes

---

.github/workflows/nextVersion.yml

add pipeline to build RC from staging branch

---

migration-2.0.0.md
src/CashuWallet.ts
src/model/types/wallet/payloads.ts

This PR aims to improve readability of the part of cashu-ts that deals with blinding and unblinding by reducing the amount of ambiguous / similar variable and type names.
- Remove `BlindTransaction` as it was not needed anymore
- Renamed `rs` to `blindingFactors
- Renames `BlindMessageData` to `BlindingData`

Streamline blinding

---

migration-2.0.0.md
src/CashuWallet.ts
src/model/types/mint/responses.ts
test/integration.test.ts
test/wallet.test.ts

Add `checkProofsStates` method to `CashuWallet` to get the spent enums from the mint, should retire `checkProofsSpent` which throws most information away.
I would prefer getting rid of `checkProofsSpent` entirely. If you agree, please delete it or let me know.
Edit: we're getting rid of `checkProofsSpent`.

Add `CashuWallet.checkProofsStates()`

---

src/utils.ts
test/utils.test.ts

This PR changes the encoding utils to default to v4 encoding if the keyset ID allows it.
Closes #198 
- added getEncodedTokenV3
- changed getEncodedToken to return v4 if possible

Default to v4 Token

---

package-lock.json
package.json
src/CashuWallet.ts
src/model/BlindedSignature.ts
src/model/types/mint/responses.ts
src/model/types/wallet/index.ts
src/model/types/wallet/tokens.ts
src/utils.ts
test/integration.test.ts
test/utils.test.ts
test/wallet.test.ts

- added optional `dleq` and `dleqValid` fields to `Proof`. `dleq` holds a `SerializedDLEQ` proof, while `dleqValid`, if present, signals whether it has been correctly verified.
- `CashuWallet.meltProofs` and `CashuWallet.createSwapPayload` strip the `dleq` field off of each `Proof`, if there is any. (No privacy leak).
- `CashuWallet.construct_proofs` now unpacks and verifies DLEQ proofs returned by the Mint, if any. It will create `Proof` with:
* `dleqValid == true` if the DLEQ is present and verified
* `dleqValid == undefined` if DLEQ not present
* `dleqValid == false` if DLEQ present and verification failed. 
- added boolean option `includeDleq` to `CashuWallet.send`:
* if `includeDleq == true`, makes sure the selected `send` proofs each have a defined `dleq` field;
* if `includeDleq == …

Support for NUT-12

---

migration-2.0.0.md
src/CashuWallet.ts
test/integration.test.ts
test/wallet.test.ts

`CashuWallet.mintProofs` used to return an object with a single key `proofs`. This PR adjusts the function to return proofs directly
- Make `mintProofs` return promised-wrapped `Array<Proof>` instead of `{proofs: Array<Proof>}`

mintProofs returns Proofs instead of object

---

.github/workflows/nutshell-integration.yml
package-lock.json
package.json
src/CashuMint.ts
src/CashuWallet.ts
src/WSConnection.ts
src/index.ts
src/model/types/index.ts
src/model/types/wallet/websocket.ts
src/utils.ts
src/ws.ts
test/WSConnection.test.ts
test/integration.test.ts
test/wallet.test.ts

This adds WebSocket management, as well as a couple of methods on CashuWallet for full NUT-17 support
- Added WSConnection Class
- Handle automatic connects and reconnects
- Added Message Queue
- Added CashuWallet methods
- Added unit and integration tests

NUT-17: WebSocket updates

---

src/model/types/mint/responses.ts
test/wallet.test.ts

nut-17: read support flags from info endpoint

---

src/CashuWallet.ts
src/model/MintInfo.ts
test/wallet.test.ts

Adds a MintInfo class that exposes some helper methods to easily check if a mint supports a NUT.
- Added MintInfo Class
- Replaced GetInfoResponse with MintInfo

Added MintInfo Class

---

src/CashuWallet.ts
src/model/types/index.ts
src/utils.ts

Some Functions in `CashuWallet` take optional paramaters, they have grown overtime, this PR move the option paramaters into a type and use the type in the function argument instead of the long object with different type,
this way we can add more optional parameters in the type and still used there ever they are need in a function 
...
- Create SendOption Type with different option parameters
- Pass SendOption as option value in function that require it.

use sendOption type in function argument

---

src/CashuAuthWallet.ts

This PR leans down the CashuAuthWallet class by removing unnecessary options and streamlining output creating using the new OutputData class.
- Removed counter & seed
- Removed split, denomination target, outputAmounts
- Removed most of the output logic and replaced it with very simple call to OutputData

Cleanup CashuAuthMint

---

package-lock.json
package.json
src/CashuWallet.ts

Restore would not work if keyset doesn't include blank output amount
- change blank output to `1` instead of `0`

Patch restore blank amounts

---

src/CashuWallet.ts
test/integration.test.ts
test/wallet.test.ts

This adds a new method to CashuWallet that automates the proofs restoration process according to the specifications recommendations.
- Adds CashuWallet.batchRestore

Add method for automated batch restoration

---

src/index.ts
src/model/OutputData.ts
src/model/types/wallet/index.ts
src/utils.ts
test/integration.test.ts

The `dleqValid` flag on the proof doesn't make sense, since it has to be verified by the receiver independently. So IMO the better approach is to just encode the dleq params, and instead expose the verification API so that the receiver can verify the proofs on receive
- remove dleqValid field from proof
- expose API

remove dleqValid from proof and expose verification api

---

src/model/PaymentRequest.ts

By refactoring, we a allow implementors to access the functionality too
- extracted `fromRawRequest`
- extracted `toRawRequest`

extracted from- and to- raw request functions

---

src/index.ts
src/model/Errors.ts
src/request.ts
test/integration.test.ts
test/request.test.ts

Error handling was not specific enough and did not even get the error `code` from a `400` response
There are a variety of errors that can occur when making a request to a mint.
- fetch fail -> instanceof NetworkError
- fetch succeeds, but status is neither 2xx nor 400 -> instanceof HttpResponseError
- fetch succeeds and status is 400 -> instanceof MintOperationError with specific Cashu Error code as defined [in the nuts](https://github.com/cashubtc/nuts/blob/main/error_codes.md)
...
- added NetworkError and MintOperationError classes
- catch fetch error and throw NetworkError
- If fetch succeeds but `!response.ok` (ie. http error), then throw MintOperationError if applicable otherwise HttpResponseError
- Export these new error classes so they can be used to handle the specific errors

handle specific errors cases in request.ts

---

src/model/types/mint/responses.ts

Replaces
```typescript
enum myEnum { val1 = 'val1',  val2 = 'val2' };
```
with
```typescript
const myEnum = { val1: 'val1', val2: 'val2'} as const;
```
and then declares a type made from the keys of the const object:
```typescript
type MyEnum = typeof MyEnum[keyof typeof MyEnum];
```
I kept the same name for both const object and type, and it doesn't seem to be creating problems nor it should because they are in different namespaces.

Replace Enums with Const Objects

---

README.md

The previous README.md used an incorrect parameter structure for the `getEncodedTokenV4` function, which caused it to fail.

Fix: Update getEncodedTokenV4 parameter format

---

src/CashuWallet.ts
test/wallet.test.ts

- `CashuWallet` does unit-based filtering of the passed keysets, if any. Throws an error if it can't find a single keyset for the specified unit (or the default unit, in case not specified).
- Unit test

Wallet Keyset Unit-Filtering on Instantiation 

---

src/model/types/wallet/index.ts
src/model/types/wallet/tokens.ts
src/utils.ts

Proof.witness field was getting dropped during serialization by getEncodedTokenV4
`witness` field added to types `Proof`, `w` added to type `V4ProofTemplate` and serialization/deserialization logic added to `tokenTemplate` and `tokenFromTemplate`.

Support for proof witness field in token serialization

---

README.md
examples/paymentApi_example.js
src/CashuWallet.ts

This changes the `amount` used to create blank output data from the melt amount to the sum of blank inputs (Math.ceil(Math.log2(22)) * 1). This way we ensure that `splitAmount` (which is being called by the OutputData methods) does not add additional outputs.

Melt: made blank output amount equal split length

---

src/WSConnection.ts

This small change makes sure to always stringify the WS URL before passing it to the `_WS` constructor. This ensures compatibility with implementations of `WebSocket` that do not handle `URL` objects.
- Pass a strigified version of URL to WebSocket constructor

Make sure to always stringify URL object for WebSockets

---

src/WSConnection.ts

The socket cancellation now check the sub listener exists and also calls removeRpcListener so that when subscribe command's response is received from the mint it will just be ignored.

Fix websocket cancellation bug

---

README.md

Added readme chapter for release strategy

Add release strategy to readme

---

src/CashuWallet.ts

This makes CashuWallet more robust by avoiding the need for apps to filter persisted keysets by unit before instantiating a CashuWallet instance.
This makes the persistence of mint keys/keysets and instantiation simpler, and prevents input/output keyset unit mismatch MintOperation errors if the app does not properly filter keysets when loading them.
- Adds a unit filter to `getActiveKeyset()`.

Ensure active keyset chosen has the wallet unit

---

src/WSConnection.ts

When socket is not open attempt to unsubscribe should be a noop instead of throwing error. Socket state can be one of the following non-open states:
- connecting - no point in unsubscribing if connection wasn't even established
- closing -  no point in unsubscribing if connection is about to be closed
- closed - no point in unsubscribing if connection is already closed
Return without doing anything instead of throwing an error in the sendRequest method.

Don't throw when unsubscribe is attempted on non open socket

---

etc/cashu-ts.api.md
src/CashuWallet.ts
src/utils.ts
test/wallet.test.ts

Adds a verification check when fetching keys from the Mint. Fails when any of the keyset ID provided by the Mint doesn't pass validation.
- added `verifyKeysetId`.
- `getKeys()` and `getAllKeys()` use `verifyKeysetId` to perfom validation.

Keyset ID verification

---

.github/workflows/consumers.yml
api-extractor.json
eslint.config.js
etc/cashu-ts.api.md
package-lock.json
package.json
post-process-dts.js
test/consumer-bundler/index.ts
test/consumer-bundler/run-test.js
test/consumer-bundler/tsconfig.json
test/consumer-commonjs/index.ts
test/consumer-commonjs/run-test.js
test/consumer-commonjs/tsconfig.json
test/consumer-iife/index.html
test/consumer-iife/run-test.js
test/consumer-iife/tsconfig.json
test/consumer-nodenext/index.ts
test/consumer-nodenext/run-test.js
test/consumer-nodenext/tsconfig.json
test/consumer-reactnative/__tests__/cashu.test.ts
test/consumer-reactnative/run-test.js
test/consumer-reactnative/tsconfig.json
vite.config.ts

Addresses build issues for NodeNext, CJS and IIFE. Adds consumer tests and workflow to ensure ongoing compatibility.
- Adds specific build tests for IIFE, CJS, Bundler and NodeNext
- Adds CI `consumers` workflow to check the build tests
- Fixes import extensions for NodeNext using dts post-processing
- Fixes CommonJS build (was using `cjs.js`, now uses `.cjs`)
- Fixes IIFE polyfills
- Adds consumer test for reactnative

Fix environment specific build issues and add consumer tests for NodeNext / CJS / IIFE / Bundler

---

src/CashuWallet.ts

I updated `createLockedMintQuote` to use lazy mint info instead of refetching every time. This matches the pattern of the rest of the methods.
- use `getLazyMintInfo` in `createLockedMintQuote` instead of `getMintInfo`

use lazy mint info in createLockedMintQuote

---

etc/cashu-ts.api.md
src/utils.ts

deriveKeysetId was causing a compile error due to a number assignment mismatch. This fixes.
- Allow number type for `versionByte`, default to 0
- throw if `versionByte` is not recognised

Fixes compile error in deriveKeysetId

---

etc/cashu-ts.api.md
src/model/types/mint/keys.ts
src/utils.ts

https://github.com/cashubtc/nuts/pull/182#issuecomment-3315077813
- Added final_expiry to GetKeysetsResponse

Add final_expiry to GetKeysetsResponse
